<script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>
<div id="<?=$map_id; ?>" class="<?=$map_class; ?>"></div>
<script type="text/javascript">
    var locations = [
<?php foreach ($locations as $i => $location):
    $title = (!empty($location['uri'])) ? '<a href="' . $location['uri'] . '"' . (($location['new_window']) ? ' target="_blank"' : '') . '>' . $location['title'] . '</a>' : $location['title'];
    $info  = str_replace(["\n", "\r"], ['', ''], $location['info']);
?>
        ['<?=$title; ?><br /><?=$info; ?>', <?=$location['latitude']; ?>, <?=$location['longitude']; ?>, <?=($i + 1); ?>],
<?php endforeach; ?>
    ];
    var map = new google.maps.Map(document.getElementById('<?=$map_id; ?>'), {
        zoom      : <?=$zoom; ?>,
        center    : new google.maps.LatLng(<?=$latitude; ?>, <?=$longitude; ?>),
        mapTypeId : google.maps.MapTypeId.<?=$map_type . PHP_EOL; ?>
    });

    var infowindow = new google.maps.InfoWindow();
    var marker, i;

    for (i = 0; i < locations.length; i++) {
        marker = new google.maps.Marker({
            position : new google.maps.LatLng(locations[i][1], locations[i][2]),
            map      : map,
<?php if (!empty($pin_icon)): ?>
            icon: '<?=BASE_PATH . $pin_icon; ?>'
<?php endif; ?>
        });

        google.maps.event.addListener(marker, 'click', (function(marker, i) {
            return function() {
                infowindow.setContent(locations[i][0]);
                infowindow.open(map, marker);
            }
        })(marker, i));
    }
</script>
