<?php include $phireHeader; ?>
    <h1 class="maps-header"><?=$title; ?></h1>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'map-locations', 'add')): ?>
        <nav><a href="<?=$phireUri . '/maps/locations/add/' . $mid; ?>">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri . '/maps/locations/' . $mid; ?>">Back</a></nav>
    </nav>
<?=$form; ?>
<?php include $phireFooter; ?>
