<?php include $phireHeader; ?>
    <h1 class="maps-header"><?=$title; ?></h1>
<?php if (count($locations) > 0): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'map-locations', 'add')): ?>
    <nav id="sub-nav">
        <nav><a href="<?=$phireUri . '/maps/locations/add/' . $mid; ?>">+ Add</a></nav>
    </nav>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'map-locations', 'remove')): ?>
    <form id="maps-form" action="<?=$phireUri . '/maps/locations/remove' . $mid; ?>" method="post">
<?php endif; ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><a href="<?=$phireUri . '/maps?sort=id';?>">#</a></th>
                <th><a href="<?=$phireUri . '/maps?sort=title';?>">Title</a></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'map-locations', 'edit')): ?>Edit<?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'map-locations', 'remove')): ?><input type="checkbox" name="checkall" id="checkall" value="rm_map_locations" /><?php else: ?>&nbsp;<?php endif; ?></th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($locations as $location): ?>
            <tr>
                <td><?=$location->id; ?></td>
                <td><?=$location->title; ?></td>
                <td><?php if ($acl->isAllowed($user->role, 'map-locations', 'edit')): ?><a class="edit-link" href="<?=$phireUri . '/maps/locations/edit/' . $mid . $location->id; ?>">Edit</a><?php else: ?>&nbsp;<?php endif; ?></td>
                <td class="text-center"><?php if ($acl->isAllowed($user->role, 'map-locations', 'remove')): ?><input type="checkbox" name="rm_map_locations[]" id="rm_map_locations<?=$i++; ?>" value="<?=$location->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
            </tr>
<?php endforeach; ?>
        </table>
<?php if ($acl->isAllowed($user->role, 'map-locations', 'remove')): ?>
        <div id="form-footer"><input type="submit" name="submit" class="process-btn" value="Remove" /></div>
    </form>
<?php endif; ?>
<?php else: ?>
<?php if ($acl->isAllowed($user->role, 'map-locations', 'add')): ?>
    <nav id="sub-nav">
        <nav><a href="<?=$phireUri . '/maps/locations/add/' . $mid; ?>">+ Add</a></nav>
    </nav>
<?php endif; ?>
    <p>There are currently no maps.</p>
<?php endif; ?>
<?php include $phireFooter; ?>